# Canonical development, validation, and release entry points for bashdeps.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

SRC_DIR := src
LIB_DIR := lib
DIST_DIR := dist
SOURCE := $(SRC_DIR)/bashdeps.bash
BASHDEPS_SOURCES := $(SOURCE)
DEV_ARTIFACT := $(DIST_DIR)/bashdeps.dev.bash
DEV_CHECKSUM := $(DEV_ARTIFACT).sha256
DIST_ARTIFACT := $(DIST_DIR)/bashdeps.bash
DIST_CHECKSUM := $(DIST_ARTIFACT).sha256
MIN_ARTIFACT := $(DIST_DIR)/bashdeps.min.bash
MIN_CHECKSUM := $(MIN_ARTIFACT).sha256

MANAGER_SOURCE := $(SRC_DIR)/manifest-manager.bash
MANAGER_LIB_SOURCES := \
	$(LIB_DIR)/manifest-manager/state.bash \
	$(LIB_DIR)/manifest-manager/manifest.bash \
	$(LIB_DIR)/manifest-manager/github.bash \
	$(LIB_DIR)/manifest-manager/transaction.bash \
	$(LIB_DIR)/manifest-manager/update.bash \
	$(LIB_DIR)/manifest-manager/list.bash
MANAGER_SOURCES := $(MANAGER_LIB_SOURCES) $(MANAGER_SOURCE)
MANAGER_DEV_ARTIFACT := $(DIST_DIR)/manifest-manager.dev.bash
MANAGER_DEV_CHECKSUM := $(MANAGER_DEV_ARTIFACT).sha256
MANAGER_DIST_ARTIFACT := $(DIST_DIR)/manifest-manager.bash
MANAGER_DIST_CHECKSUM := $(MANAGER_DIST_ARTIFACT).sha256
MANAGER_MIN_ARTIFACT := $(DIST_DIR)/manifest-manager.min.bash
MANAGER_MIN_CHECKSUM := $(MANAGER_MIN_ARTIFACT).sha256

LEGACY_CHECKSUMS := $(DIST_DIR)/SHA256SUMS

TESTS_DIR := tests
TEST_SCRIPTS := $(TESTS_DIR)/bashdeps.bats $(TESTS_DIR)/wget-capability.bats
MANAGER_TEST_SCRIPTS := $(TESTS_DIR)/manifest-manager.bats
BUILD_DEPS_TEST := $(TESTS_DIR)/build-deps.bats
TEST_HELPERS := $(TESTS_DIR)/test_helper.bash
MANAGER_TEST_HELPERS := $(TESTS_DIR)/manifest-manager-test-helper.bash
COMPAT_TEST := $(TESTS_DIR)/compat-bash.bash
MANAGER_COMPAT_TEST := $(TESTS_DIR)/compat-manifest-manager.bash

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.6
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := bb6c807fa12c010950bda06172ac0611d278c57aca1f8352f41502d0d76b4e6c
BASH_MINIFIER := $(VENDOR_DIR)/bash-minifier.bash
DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
REFERENCE_DOC_DIR := doc/reference

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check clean deps deps-check distclean docs docs-clean FORCE format test test-build-deps test-source test-dev test-dist test-min verify-bashdeps

## Synchronize development/build dependencies, then build release artifacts.
##
## The recursive Make invocation keeps ordering explicit under parallel Make.
## Plain `make build` remains network-free and consumes already-prepared vendor
## state without invoking dependency synchronization or verification.
all: deps
	$(MAKE) --no-print-directory build

build: $(BASHDEPS_SOURCES) $(MANAGER_SOURCES)
	@test -r "$(BASH_MINIFIER)" || { \
		printf '%s\n' 'Missing Bash-Minifier build dependency; run make deps first' >&2; \
		exit 1; \
	}
	mkdir -p "$(DIST_DIR)"
	rm -f "$(LEGACY_CHECKSUMS)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source: src/bashdeps.bash'; \
		printf '\n'; \
		printf '__bashdeps_version=%q\n' "$(VERSION)"; \
		printf '__bashdeps_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__bashdeps_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		sed '1{/^#!/d;}' "$(SOURCE)"; \
	} >"$(DEV_ARTIFACT).tmp"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source closure: src/manifest-manager.bash and lib/manifest-manager/*.bash'; \
		printf '\n'; \
		printf '__manifest_manager_version=%q\n' "$(VERSION)"; \
		printf '__manifest_manager_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__manifest_manager_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		for source in $(MANAGER_LIB_SOURCES); do \
			sed '1{/^#!/d;}' "$$source"; \
			printf '\n'; \
		done; \
		sed -e '1{/^#!/d;}' \
			-e '/^# BEGIN MANIFEST_MANAGER_SOURCE_IMPORTS$$/,/^# END MANIFEST_MANAGER_SOURCE_IMPORTS$$/d' \
			"$(MANAGER_SOURCE)"; \
	} >"$(MANAGER_DEV_ARTIFACT).tmp"
	sed -e '1b' -e '/^[[:space:]]*#/d' "$(DEV_ARTIFACT).tmp" >"$(DIST_ARTIFACT).tmp"
	sed -e '1b' -e '/^[[:space:]]*#/d' "$(MANAGER_DEV_ARTIFACT).tmp" >"$(MANAGER_DIST_ARTIFACT).tmp"
	bash "$(BASH_MINIFIER)" -F <"$(DIST_ARTIFACT).tmp" >"$(MIN_ARTIFACT).tmp"
	bash "$(BASH_MINIFIER)" -F <"$(MANAGER_DIST_ARTIFACT).tmp" >"$(MANAGER_MIN_ARTIFACT).tmp"
	@if grep -q '__manifest_manager_' "$(DEV_ARTIFACT).tmp"; then \
		printf '%s\n' 'bashdeps developer artifact contains manifest-manager code' >&2; \
		exit 1; \
	fi
	@if grep -q '__bashdeps_' "$(MANAGER_DEV_ARTIFACT).tmp"; then \
		printf '%s\n' 'manifest-manager developer artifact contains bashdeps runtime code' >&2; \
		exit 1; \
	fi
	chmod 0755 \
		"$(DEV_ARTIFACT).tmp" "$(DIST_ARTIFACT).tmp" "$(MIN_ARTIFACT).tmp" \
		"$(MANAGER_DEV_ARTIFACT).tmp" "$(MANAGER_DIST_ARTIFACT).tmp" "$(MANAGER_MIN_ARTIFACT).tmp"
	mv "$(DEV_ARTIFACT).tmp" "$(DEV_ARTIFACT)"
	mv "$(DIST_ARTIFACT).tmp" "$(DIST_ARTIFACT)"
	mv "$(MIN_ARTIFACT).tmp" "$(MIN_ARTIFACT)"
	mv "$(MANAGER_DEV_ARTIFACT).tmp" "$(MANAGER_DEV_ARTIFACT)"
	mv "$(MANAGER_DIST_ARTIFACT).tmp" "$(MANAGER_DIST_ARTIFACT)"
	mv "$(MANAGER_MIN_ARTIFACT).tmp" "$(MANAGER_MIN_ARTIFACT)"
	@if command -v sha256sum >/dev/null 2>&1; then \
		cd "$(DIST_DIR)"; \
		sha256sum "$(notdir $(DEV_ARTIFACT))" >"$(notdir $(DEV_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(DIST_ARTIFACT))" >"$(notdir $(DIST_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(MIN_ARTIFACT))" >"$(notdir $(MIN_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(MANAGER_DEV_ARTIFACT))" >"$(notdir $(MANAGER_DEV_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(MANAGER_DIST_ARTIFACT))" >"$(notdir $(MANAGER_DIST_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(MANAGER_MIN_ARTIFACT))" >"$(notdir $(MANAGER_MIN_CHECKSUM)).tmp"; \
	elif command -v shasum >/dev/null 2>&1; then \
		cd "$(DIST_DIR)"; \
		shasum -a 256 "$(notdir $(DEV_ARTIFACT))" >"$(notdir $(DEV_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(DIST_ARTIFACT))" >"$(notdir $(DIST_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(MIN_ARTIFACT))" >"$(notdir $(MIN_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(MANAGER_DEV_ARTIFACT))" >"$(notdir $(MANAGER_DEV_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(MANAGER_DIST_ARTIFACT))" >"$(notdir $(MANAGER_DIST_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(MANAGER_MIN_ARTIFACT))" >"$(notdir $(MANAGER_MIN_CHECKSUM)).tmp"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi
	mv "$(DEV_CHECKSUM).tmp" "$(DEV_CHECKSUM)"
	mv "$(DIST_CHECKSUM).tmp" "$(DIST_CHECKSUM)"
	mv "$(MIN_CHECKSUM).tmp" "$(MIN_CHECKSUM)"
	mv "$(MANAGER_DEV_CHECKSUM).tmp" "$(MANAGER_DEV_CHECKSUM)"
	mv "$(MANAGER_DIST_CHECKSUM).tmp" "$(MANAGER_DIST_CHECKSUM)"
	mv "$(MANAGER_MIN_CHECKSUM).tmp" "$(MANAGER_MIN_CHECKSUM)"

## Force the bootstrap file target to validate cached bytes whenever requested.
FORCE:

## Bootstrap the pinned released bashdeps executable used to process dependencies.txt.
##
## Make directly owns only this bootstrap dependency. Correct cached bytes avoid
## network access. Missing or mismatched bytes are replaced only after a staged
## download matches the committed SHA-256 digest.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			actual="$$(shasum -a 256 "$$path" | awk '{print $$1}')"; \
			[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
		else \
			return 2; \
		fi; \
	}; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	if [[ -f "$@" ]] && verify_hash "$@"; then \
		chmod 0755 "$@"; \
		exit 0; \
	fi; \
	if ! command -v curl >/dev/null 2>&1; then \
		printf '%s\n' 'curl is required to bootstrap bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	tmp="$@.tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	if ! verify_hash "$$tmp"; then \
		printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; \
		exit 1; \
	fi; \
	chmod 0755 "$$tmp"; \
	mv "$$tmp" "$@"; \
	trap - EXIT

## Verify the already-present bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { \
		printf '%s\n' 'Missing or non-executable bashdeps bootstrap; run make deps' >&2; \
		exit 1; \
	}
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')"; \
		[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi

## Synchronize manifest-managed development/build dependencies through released bashdeps.
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

## Verify bootstrap and manifest-managed state without network access or repair.
deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

check:
	bash -n "$(SOURCE)" "$(MANAGER_SOURCE)" $(MANAGER_LIB_SOURCES) $(TEST_HELPERS) $(MANAGER_TEST_HELPERS) "$(COMPAT_TEST)" "$(MANAGER_COMPAT_TEST)"
	shellcheck -x -P . "$(SOURCE)" "$(MANAGER_SOURCE)"

format:
	shfmt -w -i 2 -ci "$(SOURCE)" "$(MANAGER_SOURCE)" $(MANAGER_LIB_SOURCES) $(TEST_HELPERS) $(MANAGER_TEST_HELPERS) "$(COMPAT_TEST)" "$(MANAGER_COMPAT_TEST)"

test: test-source test-dev test-dist test-min test-build-deps

test-source:
	BASHDEPS_EXECUTABLE="$(SOURCE)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(SOURCE)" bash "$(COMPAT_TEST)"
	MANIFEST_MANAGER_EXECUTABLE="$(MANAGER_SOURCE)" bats $(MANAGER_TEST_SCRIPTS)
	MANIFEST_MANAGER_EXECUTABLE="$$(pwd)/$(MANAGER_SOURCE)" bash "$(MANAGER_COMPAT_TEST)"

test-dev: build
	bash -n "$(DEV_ARTIFACT)" "$(MANAGER_DEV_ARTIFACT)"
	test -x "$(DEV_ARTIFACT)"
	test -x "$(MANAGER_DEV_ARTIFACT)"
	test "$$(sed -n '1p' "$(DEV_ARTIFACT)")" = '#!/usr/bin/env bash'
	test "$$(sed -n '1p' "$(MANAGER_DEV_ARTIFACT)")" = '#!/usr/bin/env bash'
	BASHDEPS_EXECUTABLE="$(DEV_ARTIFACT)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(DEV_ARTIFACT)" bash "$(COMPAT_TEST)"
	MANIFEST_MANAGER_EXECUTABLE="$(MANAGER_DEV_ARTIFACT)" bats $(MANAGER_TEST_SCRIPTS)
	MANIFEST_MANAGER_EXECUTABLE="$$(pwd)/$(MANAGER_DEV_ARTIFACT)" bash "$(MANAGER_COMPAT_TEST)"
	cd "$(DIST_DIR)" && if command -v sha256sum >/dev/null 2>&1; then sha256sum -c "$(notdir $(DEV_CHECKSUM))" "$(notdir $(MANAGER_DEV_CHECKSUM))"; else shasum -a 256 -c "$(notdir $(DEV_CHECKSUM))" "$(notdir $(MANAGER_DEV_CHECKSUM))"; fi

test-dist: build
	bash -n "$(DIST_ARTIFACT)" "$(MANAGER_DIST_ARTIFACT)"
	test -x "$(DIST_ARTIFACT)"
	test -x "$(MANAGER_DIST_ARTIFACT)"
	test "$$(sed -n '1p' "$(DIST_ARTIFACT)")" = '#!/usr/bin/env bash'
	test "$$(sed -n '1p' "$(MANAGER_DIST_ARTIFACT)")" = '#!/usr/bin/env bash'
	@if tail -n +2 "$(DIST_ARTIFACT)" | grep -Eq '^[[:space:]]*#'; then \
		printf '%s\n' 'Comment-stripped bashdeps artifact still contains full-line comments' >&2; \
		exit 1; \
	fi
	@if tail -n +2 "$(MANAGER_DIST_ARTIFACT)" | grep -Eq '^[[:space:]]*#'; then \
		printf '%s\n' 'Comment-stripped manifest-manager artifact still contains full-line comments' >&2; \
		exit 1; \
	fi
	BASHDEPS_EXECUTABLE="$(DIST_ARTIFACT)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(DIST_ARTIFACT)" bash "$(COMPAT_TEST)"
	MANIFEST_MANAGER_EXECUTABLE="$(MANAGER_DIST_ARTIFACT)" bats $(MANAGER_TEST_SCRIPTS)
	MANIFEST_MANAGER_EXECUTABLE="$$(pwd)/$(MANAGER_DIST_ARTIFACT)" bash "$(MANAGER_COMPAT_TEST)"
	cd "$(DIST_DIR)" && if command -v sha256sum >/dev/null 2>&1; then sha256sum -c "$(notdir $(DIST_CHECKSUM))" "$(notdir $(MANAGER_DIST_CHECKSUM))"; else shasum -a 256 -c "$(notdir $(DIST_CHECKSUM))" "$(notdir $(MANAGER_DIST_CHECKSUM))"; fi
	test ! -e "$(LEGACY_CHECKSUMS)"

test-min: build
	bash -n "$(MIN_ARTIFACT)" "$(MANAGER_MIN_ARTIFACT)"
	test -x "$(MIN_ARTIFACT)"
	test -x "$(MANAGER_MIN_ARTIFACT)"
	test "$$(sed -n '1p' "$(MIN_ARTIFACT)")" = '#!/usr/bin/env bash'
	test "$$(sed -n '1p' "$(MANAGER_MIN_ARTIFACT)")" = '#!/usr/bin/env bash'
	BASHDEPS_EXECUTABLE="$(MIN_ARTIFACT)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(MIN_ARTIFACT)" bash "$(COMPAT_TEST)"
	MANIFEST_MANAGER_EXECUTABLE="$(MANAGER_MIN_ARTIFACT)" bats $(MANAGER_TEST_SCRIPTS)
	MANIFEST_MANAGER_EXECUTABLE="$$(pwd)/$(MANAGER_MIN_ARTIFACT)" bash "$(MANAGER_COMPAT_TEST)"
	cd "$(DIST_DIR)" && if command -v sha256sum >/dev/null 2>&1; then sha256sum -c "$(notdir $(MIN_CHECKSUM))" "$(notdir $(MANAGER_MIN_CHECKSUM))"; else shasum -a 256 -c "$(notdir $(MIN_CHECKSUM))" "$(notdir $(MANAGER_MIN_CHECKSUM))"; fi
	test ! -e "$(LEGACY_CHECKSUMS)"

## Exercise Make/bootstrap/dependency boundaries once per test run.
test-build-deps:
	bats "$(BUILD_DEPS_TEST)"

## Remove generated Doxygen reference documentation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

## Generate browsable Doxygen reference documentation from maintained Bash source.
##
## The filter is manifest-managed data. The documentation consumer applies the
## executable mode Doxygen needs rather than asking bashdeps to infer file purpose.
docs: docs-clean deps
	chmod 0755 "$(DOXYGEN_BASH_FILTER)"
	mkdir -p "$(REFERENCE_DOC_DIR)"
	doxygen Doxyfile

clean:
	rm -rf "$(DIST_DIR)"

## Remove ordinary build output, generated reference docs, and generated vendor state.
distclean: clean docs-clean
	rm -rf "$(VENDOR_DIR)"
