# Canonical development, validation, and release entry points for bashdeps.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

SRC_DIR := src
DIST_DIR := dist
SOURCE := $(SRC_DIR)/bashdeps.bash
DEV_ARTIFACT := $(DIST_DIR)/bashdeps.dev.bash
DIST_ARTIFACT := $(DIST_DIR)/bashdeps.bash
CHECKSUMS := $(DIST_DIR)/SHA256SUMS

TESTS_DIR := tests
TEST_SCRIPTS := $(TESTS_DIR)/*.bats
TEST_HELPERS := $(TESTS_DIR)/test_helper.bash
COMPAT_TEST := $(TESTS_DIR)/compat-bash.bash

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check clean format test test-source test-dev test-dist

all: build

build: $(SOURCE)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source: src/bashdeps.bash'; \
		printf '\n'; \
		printf '__bashdeps_version=%q\n' "$(VERSION)"; \
		printf '__bashdeps_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__bashdeps_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		sed '1{/^#!/d;}' "$(SOURCE)"; \
	} >"$(DEV_ARTIFACT).tmp"
	chmod 0755 "$(DEV_ARTIFACT).tmp"
	mv "$(DEV_ARTIFACT).tmp" "$(DEV_ARTIFACT)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source: src/bashdeps.bash'; \
		printf '\n'; \
		printf '__bashdeps_version=%q\n' "$(VERSION)"; \
		printf '__bashdeps_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__bashdeps_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		sed '1{/^#!/d;}; /^[[:space:]]*#/d' "$(SOURCE)"; \
	} >"$(DIST_ARTIFACT).tmp"
	chmod 0755 "$(DIST_ARTIFACT).tmp"
	mv "$(DIST_ARTIFACT).tmp" "$(DIST_ARTIFACT)"
	@if command -v sha256sum >/dev/null 2>&1; then \
		cd "$(DIST_DIR)" && sha256sum "$(notdir $(DEV_ARTIFACT))" "$(notdir $(DIST_ARTIFACT))" >"$(notdir $(CHECKSUMS)).tmp"; \
	elif command -v shasum >/dev/null 2>&1; then \
		cd "$(DIST_DIR)" && shasum -a 256 "$(notdir $(DEV_ARTIFACT))" "$(notdir $(DIST_ARTIFACT))" >"$(notdir $(CHECKSUMS)).tmp"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi
	mv "$(CHECKSUMS).tmp" "$(CHECKSUMS)"

check:
	bash -n "$(SOURCE)" $(TEST_HELPERS) "$(COMPAT_TEST)"
	shellcheck "$(SOURCE)" $(TEST_HELPERS) "$(COMPAT_TEST)"

format:
	shfmt -w -i 2 -ci "$(SOURCE)" $(TEST_HELPERS) "$(COMPAT_TEST)"

test: test-source test-dev test-dist

test-source:
	BASHDEPS_EXECUTABLE="$(SOURCE)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(SOURCE)" bash "$(COMPAT_TEST)"

test-dev: build
	bash -n "$(DEV_ARTIFACT)"
	test -x "$(DEV_ARTIFACT)"
	test "$$(sed -n '1p' "$(DEV_ARTIFACT)")" = '#!/usr/bin/env bash'
	BASHDEPS_EXECUTABLE="$(DEV_ARTIFACT)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(DEV_ARTIFACT)" bash "$(COMPAT_TEST)"

test-dist: build
	bash -n "$(DIST_ARTIFACT)"
	test -x "$(DIST_ARTIFACT)"
	test "$$(sed -n '1p' "$(DIST_ARTIFACT)")" = '#!/usr/bin/env bash'
	BASHDEPS_EXECUTABLE="$(DIST_ARTIFACT)" bats $(TEST_SCRIPTS)
	BASHDEPS_EXECUTABLE="$$(pwd)/$(DIST_ARTIFACT)" bash "$(COMPAT_TEST)"
	cd "$(DIST_DIR)" && if command -v sha256sum >/dev/null 2>&1; then sha256sum -c "$(notdir $(CHECKSUMS))"; else shasum -a 256 -c "$(notdir $(CHECKSUMS))"; fi

clean:
	rm -rf "$(DIST_DIR)"
